version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: flight-mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_LOCAL_PORT

  api-server:
    build: .
    container_name: flight-api-server
    env_file: ./.env
    depends_on:
      - "mysql"
    environment:
      - API_SERVER_PORT=$API_SERVER_PORT
    ports:
      - $API_SERVER_PORT:$API_SERVER_PORT
    networks:
      - demo-network

networks:
  demo-network:
