version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: flight-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "flight-ticket-system"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./mysql/mysql_schema:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - 3306:3306

networks:
  demo-network:
