version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: flight-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "flight-ticket"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - 3306:3306

  api-server:
    build: .
    container_name: flight-api-server
    depends_on:
      - "mysql"
    ports:
      - "8080:8080"
    networks:
      - demo-network

networks:
  demo-network:
